online_exam/examapp/urls.py
from django.urls import path, re_path

from . import views

# 增加域名空间
app_name = 'examapp'
urlpatterns = [
    path('', views.start_page, name='start'),
    path('login/', views.user_login, name='login'),
    path('stuHome/<username>', views.stu_home, name='stuHome'),
    path('teacherHome/<username>', views.teacher_home, name='teacherHome'),
    re_path(r'^calculateScore/$', views.calculate_score, name='calculateScore'),
    re_path(r'^exam/$', views.startExam, name='exam'),
]

online_exam/online_exam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('examapp.urls')),
]

online_exam/examapp/models.py
from datetime import datetime, timedelta

from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
SEX = (
    # value  display name
    ('male', '男'),  # max_length = 4 + 2 = 6
    ('female', '女'),
)

ACADEMY = (
    ('cs', '计算机科学与技术学院'),
    ('art', '艺术学院'),
)

# 题目难度
LEVEL = {
    ('level1', 'easy'),
    ('level2', 'general'),
    ('level3', 'difficult'),
}


# 用户
class User(AbstractUser):
    """
    用户类模型
    """
    # student.username -----> 学号
    # teacher.username -----> 教职工号
    # admin.username   -----> 管理员账号
    username = models.CharField(max_length=30, verbose_name="学号/教职工号", primary_key=True)  # 这里就是创建超级用户的唯一凭证
    # 这里如果给了password这个属性的话，那边验证不通过
    # password = models.CharField(max_length=20, verbose_name='用户密码', default='123456')
    real_name = models.CharField(max_length=30, verbose_name="姓名")
    sex = models.CharField('性别', max_length=10, choices=SEX, default='男')
    academy = models.CharField('学院', max_length=20, choices=ACADEMY, default='cs')
    is_teacher = models.BooleanField(verbose_name="是否为老师", default=False)
    class_name = models.CharField(max_length=50, verbose_name="班级", blank=True, default='1班')

    def __str__(self):
        return self.username

    class Meta:
        verbose_name_plural = '用户'  # 在管理界面中表的名字
        ordering = ['class_name']  # 在管理界面按照班级名称排序


# 三种题型：单项选择题、填空题、判断题
class ChoiceQuestion(models.Model):
    ANSWER = (
        ('optA', 'A'),
        ('optB', 'B'),
        ('optC', 'C'),
        ('optD', 'D'),
    )
    # id = models.AutoField(primary_key=True) 自动加入
    # subject = models.CharField(max_length=20, verbose_name='科目')
    id = models.IntegerField(primary_key=True, verbose_name='题目编号', default=1)
    title = models.TextField(verbose_name='题目描述')
    answer = models.CharField(max_length=10, choices=ANSWER, verbose_name='答案')
    level = models.CharField(max_length=10, choices=LEVEL, verbose_name='题目难度')
    score = models.IntegerField(verbose_name='该题分数', default=1)

    optionA = models.TextField(max_length=30, verbose_name='A选项')
    optionB = models.TextField(max_length=30, verbose_name='B选项')
    optionC = models.TextField(max_length=30, verbose_name='C选项')
    optionD = models.TextField(max_length=30, verbose_name='D选项')

    def __str__(self):
        """
        提供组卷信息
        :return:
        """
        return '(%s): %s' % (self.id, self.title)


class JudgeQuestion(models.Model):
    ANSWER = (
        ('T', '正确'),
        ('F', '错误'),
    )
    # subject = models.CharField(max_length=20, verbose_name='科目')
    id = models.IntegerField(primary_key=True, verbose_name='题目编号', default=1)
    title = models.TextField(verbose_name='题目描述')
    answer = models.CharField(max_length=20, choices=ANSWER)
    level = models.CharField(max_length=10, choices=LEVEL, verbose_name='题目难度')
    score = models.IntegerField(verbose_name='该题分数', default=1)

    def __str__(self):
        """
        提供组卷信息
        :return:
        """
        return '(%s): %s' % (self.id, self.title)


class FillBlankQuestion(models.Model):
    # subject = models.CharField(max_length=20, verbose_name='科目')
    id = models.IntegerField(primary_key=True, verbose_name='题目编号', default=1)
    title = models.TextField(verbose_name='题目描述')
    answer = models.CharField(max_length=200, verbose_name='答案')
    level = models.CharField(max_length=10, choices=LEVEL, verbose_name='题目难度')
    score = models.IntegerField(verbose_name='该题分数', default=2)

    def __str__(self):
        """
        提供组卷信息
        :return:
        """
        return '(%s): %s' % (self.id, self.title)


def now_plus_1(day=1, hour=0):
    return datetime.now() + timedelta(days=day, hours=hour)


class Paper(models.Model):
    # 与题库为多对多关系
    id = models.IntegerField(primary_key=True, verbose_name='试卷编号', default=1)

    choice_q = models.ManyToManyField(ChoiceQuestion, verbose_name='选择题')
    # blank = True----> ManyToManyField optional
    judge_q = models.ManyToManyField(JudgeQuestion, verbose_name='判断题', blank=True)
    fill_blank_q = models.ManyToManyField(FillBlankQuestion, verbose_name='填空题', blank=True)

    # User作为外键
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='出题人')
    subject = models.CharField(max_length=20, verbose_name='考试科目', default='Python')
    academy = models.CharField(max_length=20, verbose_name='适用学院', default='cs')
    exam_start_time = models.DateTimeField(verbose_name='考试开始时间', default=now_plus_1)
    exam_stop_time = models.DateTimeField(verbose_name='考试结束时间', default=now_plus_1(hour=2))

    class Meta:
        verbose_name_plural = '试卷'  # 在管理界面中表的名字


class Grade(models.Model):
    # 学生作为成绩的外键
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=20, verbose_name='科目')
    grade = models.IntegerField()

    def __str__(self):
        return '<%s:%s>' % (self.sid, self.grade);

    class Meta:
        verbose_name_plural = '成绩'

online_exam/examapp/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect, get_object_or_404

from . import models


# Create your views here.

def start_page(request):
    """
    起始页面(跳转到登陆界面)
    """
    return redirect('examapp:login')


# 用户登陆
def user_login(request):
    """
    用户登陆页面
    """
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        # print(username, password)
        # user = get_object_or_404(models.User, username=username, is_teacher=False)
        user = authenticate(request, username=username, password=password)
        if user is not None:
            # print('user 有')
            login(request, user)
            # return redirect('examapp:home', username = user.username)
            if user.is_teacher:
                return redirect('examapp:teacherHome', username=user.username)
            else:
                return redirect('examapp:stuHome', username=user.username)
        else:
            # 是在这里调用的登录模板
            return render(request, 'login.html', {'error': '密码错误'})
    else:
        return render(request, 'login.html')


# 学生登陆之后的home_page
def stu_home(request, username):
    # 其中get_object_or_404()第一个参数是对象，后面都是这个对象要满足的条件
    # 可以不需要用下面这种方式获取学生实体
    # 通过学号获取该学生实体
    # student = models.Student.objects.get(username=username)
    student = get_object_or_404(models.User, username=username, is_teacher=False)
    # 查询考试信息，根据学生所在学院查询要考的试题
    paper = models.Paper.objects.filter(academy=student.academy)
    # 查询成绩信息
    grade = models.Grade.objects.filter(student=student.username)
    context = {
        'student': student,
        'paper': paper,
        'grade': grade,
    }
    return render(request, 'stuHome.html', context)


# 老师登陆之后的home_page
def teacher_home(request, username):
    teacher = get_object_or_404(models.User, username=username, is_teacher=True)

    # 在试卷表 paper 找到该老师发布的试题
    paper = models.Paper.objects.filter(author=teacher.username)

    context = {
        'teacher': teacher,
        'paper': paper,
    }

    return render(request, 'teacherHome.html', context)


# 学生考试 的视图函数
def startExam(request):
    username = request.GET.get('sid')
    paper_id = request.GET.get('pid')
    subject = request.GET.get('subject')

    student = get_object_or_404(models.User, username=username, is_teacher=False)
    # 确保学生唯一的一张考试试题
    paper = get_object_or_404(models.Paper, id=paper_id)

    context = {
        'student': student,
        'paper': paper,
        'subject': subject,
    }

    return render(request, 'exam.html', context)


# 计算由exam.html模版传过来的数据计算成绩
def calculate_score(request):
    if request.method == 'POST':
        sid      = request.POST['sid']
        pid      = request.POST['pid']
        subject = request.POST['subject']

        # 重新生成Student实例，Paper实例，Grade实例，名字和index中for的一致，可重复渲染
        student = models.User.objects.get(username=sid)
        paper   = models.Paper.objects.filter(id=pid)
        grade   = models.Grade.objects.filter(student=student.username)

        mygrade  = 0  # 初始化一个成绩为0

        # 选择题成绩
        # 其中models.Paper.objects.filter(id=pid).values('choice_q')，返回id=pid的试卷中所有的选择题(集合，可迭代)
        choice_q = models.Paper.objects.filter(id=pid).values('choice_q').values('choice_q__id', 'choice_q__answer',
                                                                                 'choice_q__score')
        for q in choice_q:
            qid = 'choice' + str(q['choice_q__id'])  # 这里一定要与exam.html中对应的name一致
            # 直接用 myans = request.POST[qid]，如果该题没有做，就会引发“MultiValueDictKeyError”
            # myans = request.POST[qid]  # 通过 qid 得到学生关于该题的作答
            myans = request.POST.get(qid)  # 通过 qid 得到学生关于该题的作答
            # print('myans', myans)
            okans = q['choice_q__answer']  # 得到正确答案
            # print('okans', okans)
            if myans == okans:  # 判断学生作答与正确答案是否一致
                mygrade += q['choice_q__score']  # 若一致,得到该题的分数,累加mygrade变量
            print('mygrade', mygrade)


        # 判断题成绩
        judge_q = models.Paper.objects.filter(id=pid).values('judge_q').values('judge_q__id', 'judge_q__answer',
                                                                               'judge_q__score')
        for q in judge_q:
            qid = 'judge' + str(q['judge_q__id'])
            myans = request.POST.get(qid)
            print('myans', myans)
            okans = q['judge_q__answer']  # 得到正确答案
            print('okans', okans)
            if myans == okans:  # 判断学生作答与正确答案是否一致
                mygrade += q['judge_q__score']  # 若一致,得到该题的分数,累加mygrade变量

        # 填空题成绩
        fill_blank_q = models.Paper.objects.filter(id=pid).values('fill_blank_q').values('fill_blank_q__id',
                                                                                         'fill_blank_q__answer',
                                                                                         'fill_blank_q__score')
        for q in fill_blank_q:
            qid = 'fill_blank' + str(q['fill_blank_q__id'])
            myans = request.POST.get(qid)
            print('myans', myans)
            okans = q['fill_blank_q__answer']  # 得到正确答案
            print('okans', okans)
            if myans == okans:  # 判断学生作答与正确答案是否一致
                mygrade += q['fill_blank_q__score']  # 若一致,得到该题的分数,累加mygrade变量

        # 向Grade表中插入数据          外键
        models.Grade.objects.create(student_id=sid, subject=subject, grade=mygrade)
        print(mygrade)
        # 重新渲染index.html模板
        return render(request, 'stuHome.html', {'student': student, 'paper': paper, 'grade': grade})

online_exam/examapp/templates/exam.html
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html;charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>在线答题考试系统</title>

    <link href="../static/home/bootstrap-4.3.1-dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- 必须在引入bootstarp.js之前引入 -->
    <script src="../static/home/jquery-3.3.1.min.js"></script>

    <script src="../static/home/bootstrap-4.3.1-dist/js/bootstrap.min.js"></script>

    <script src="../static/home/js/jquery-1.11.3.min.js"></script>
    <script src="../static/home/js/jquery.countdown.js"></script>
    <!--时间js-->
    <link href="../static/home/css/main.css" rel="stylesheet" type="text/css"/>

    <link href="../static/home/css/test.css" rel="stylesheet" type="text/css"/>
    <style>
        .hasBeenAnswer {
            background: #5d9cec;
            color: #fff;
        }
    </style>

</head>
<body>

<nav class="navbar navbar-expand-sm bg-light navbar-light ">
    <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link"><h3>在线考试系统</h3></a>
        </li>

        <li class="nav-item active">
            <a class="nav-link"><h3>当前科目:{{ subject }}</h3></a>
        </li>
        <li style="position: fixed;right: 70px; font-size: 30px;color: #9fcdff">{{ student.real_name }}</li>

    </ul>
</nav>

<div class="main">
    <!--nr start-->
    <div class="test_main">
        <div class="nr_left">
            <div class="test">
                <form action="{% url 'examapp:calculateScore' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="sid" value="{{ student.username }}">
                    <input type="hidden" name="pid" value="{{ paper.id }}">
                    <input type="hidden" name="subject" value="{{ subject }}">
                    <div class="test_title">
                        <font><input type="submit" name="submit_paper" value="交卷"></font>
                    </div>


                    <!--选择题-->
                    <div class="choice_content">
                        <div class="choice_content_title">
                            <h2>单选题</h2>
                        </div>
                    </div>
                    <div class="choice_content_nr">
                        <ul>
                            {% for choice in paper.choice_q.all %}
                            <li id="choice {{ forloop.counter }}">
                                <div class="choice_content_nr_tt">
                                    <i>{{ forloop.counter}}</i><span> ({{ choice.score }} 分)</span>
                                    <font>{{ choice.title }}</font>

                                </div>
                                <div class="choice_content_nr_main">
                                    <ul>
                                        <li class="option">
                                            <input type="radio" class="radioOrCheck" name="choice{{ choice.id }}"
                                                   value="optA"/>
                                            <label>A.
                                                <p class="ue" style="display: inline;">{{ choice.optionA }}</p>
                                            </label>
                                        </li>

                                        <li class="option">
                                            <input type="radio" class="radioOrCheck" name="choice{{ choice.id }}"
                                                   value="optB"/>
                                            <label>
                                                B.<p class="ue" style="display: inline;">{{ choice.optionB }}</p>
                                            </label>
                                        </li>

                                        <li class="option">
                                            <input type="radio" class="radioOrCheck" name="choice{{ choice.id }}"
                                                   value="optC"/>
                                            <label>
                                                C.<p class="ue" style="display: inline;">{{ choice.optionC }}</p>
                                            </label>
                                        </li>

                                        <li class="option">
                                            <input type="radio" class="radioOrCheck" name="choice{{ choice.id }}"
                                                   value="optD"/>
                                            <label>
                                                D.<p class="ue" style="display: inline;">{{ choice.optionD }}</p>
                                            </label>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>


                    <!--判断题-->
                    <div class="judge_content">
                        <div class="judge_content_title">
                            <h2>判断题</h2>
                        </div>
                    </div>
                    <div class="judge_content_nr">
                        <ul>
                            {% for judge in paper.judge_q.all %}
                            <li id="judge {{ forloop.counter }}">
                                <div class="judge_content_nr_tt">
                                    <i>{{ forloop.counter}}</i><span> ({{ judge.score }} 分)</span>
                                    <font>{{ judge.title }}</font>

                                </div>
                            <li class="judge">
                                <input type="radio" class="radioOrCheck" name="judge{{ judge.id }}"
                                       value="T"/>
                                <label>
                                    正确
                                </label>
                            </li>

                            <li class="judge">
                                <input type="radio" class="radioOrCheck" name="judge{{ judge.id }}"
                                       value="F"/>
                                <label>
                                    错误
                                </label>
                            </li>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>


                    <!--填空题-->
                    <div class="fill_blank_content">
                        <div class="fill_blank_content_title">
                            <h2>填空题</h2>
                        </div>
                    </div>
                    <div class="fill_blank_content_nr">
                        <ul>
                            {% for fill_blank in paper.fill_blank_q.all %}
                            <li id="fill_blank {{ forloop.counter }}">
                                <div class="fill_blank_content_nr_tt">
                                    <i>{{ forloop.counter}}</i><span> ({{ fill_blank.score }} 分)</span>
                                    <font>{{ fill_blank.title }}</font>

                                </div>
                            <li class="fill_blank">
                                <div class="form-floating">
                                    <textarea class="form-control" placeholder="写上你的答案"
                                              name="fill_blank{{ fill_blank.id }}"
                                              value="{{ fill_blank.answer}}"
                                              id="floatingTextarea"></textarea>
                                </div>
                            </li>

                            </li>
                            {% endfor %}
                        </ul>
                    </div>


                </form>
            </div>
        </div>

    </div>
    <div class="foot"></div>
</div>


</body>
</html>

online_exam/examapp/templates/login.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="en">
    <title></title>
    <link rel="stylesheet" type="text/css" href="{% static 'login/login.css' %}"/>

</head>
<body>

<div class="login-box">
    <h2>Login</h2>
    <div class="login_name">
        <p>数据库考试平台登录</p>
    </div>
    <form action="{% url 'examapp:login' %}" method="post">
        {% csrf_token %}
        <div class="login-field">
            <input type="text" name="username" required=""/>
            <label>Username</label>
        </div>
        <div class="login-field">
            <input type="password" name="password" required=""/>
            <label>Password</label>
        </div>
        <button type="submit">Submit</button>
    </form>
</div>

<!--Footer-->
<footer class="footer_third">
    <div class="copyright">© 电子科技大学™</div>
</footer>


</body>
</html>

online_exam/examapp/templates/stuHome.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="../static/home/bootstrap-4.3.1-dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="../static/home/jquery-3.3.1.min.js"></script>

    <script src="../static/home/bootstrap-4.3.1-dist/js/bootstrap.min.js"></script>

    <link href="../static/home/css/index.css" rel="stylesheet">

    <title>在线考试系统</title>

</head>
<body>

<nav class="navbar navbar-expand-sm bg-light navbar-light ">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="/login/">切换登录用户</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="/admin/">管理员</a>
        </li>


        <li style="position: fixed;right: 70px; font-size: 40px;color: #9fcdff">{{ student.real_name }}{{ message }}
        </li>
        <a href="/logout/">
            <li style="position: fixed;right: 20px; font-size: 20px;top:22px;color:#cc1313">退出</li>
        </a>

    </ul>
</nav>

<div class="container">

    <br>
    <!-- Nav pills -->
    <ul class="nav nav-pills" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="pill" href="#home">个人信息</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="pill" href="#menu1">考试信息</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="pill" href="#menu2">成绩查询</a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div id="home" class="container tab-pane active"><br>
            <h3>个人信息</h3>

            <table class="table">
                <thead>
                <tr>
                    <th>属性</th>
                    <th>信息</th>

                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>学号</td>
                    <td>{{ student.username }}</td>

                </tr>
                <tr class="table-primary">
                    <td>姓名</td>
                    <td>{{ student.real_name }}</td>

                </tr>
                <tr class="table-success">
                    <td>性别</td>
                    <td>{{ student.sex }}</td>

                </tr>
                <tr class="table-danger">
                    <td>学院</td>
                    <td>{{ student.academy }}</td>

                </tr>
                <tr class="table-active">
                    <td>班级</td>
                    <td>{{ student.class_name }}</td>
                </tr>

                </tbody>
            </table>
        </div>

        <div id="menu1" class="container tab-pane fade"><br>
            <h3>考试信息</h3>
            <p></p>
            <table class="table">
                <thead>
                <tr>
                    <th>姓名</th>
                    <th>考试科目</th>
                    <th>考试开始时间</th>
                    <th>考试结束时间</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {# 遍历字典 paper #}
                {% for paper1 in paper %}

                <tr class="table-info">
                    <td>{{ student.real_name }}</td>
                    <td>{{ paper1.subject }}</td>
                    <td>{{ paper1.exam_start_time }} {{ paper2.examtime }}</td>
                    <td>{{ paper1.exam_stop_time }}</td>
                    <td>
                        <a href="/exam/?sid={{ student.username }}&pid={{ paper1.id }}&subject={{ paper1.subject }}">
                            <button class="btn btn-primary" id="toExam+{{ paper1.subject }}">开始考试</button>
                        </a>
                    </td>
                </tr>
                {% endfor %}


                </tbody>
            </table>
        </div>

        <div id="menu2" class="container tab-pane fade"><br>
            <h3>考试成绩</h3>
            <p></p>
            <table class="table">
                <thead>
                <tr>
                    <th>姓名</th>
                    <th>科目</th>
                    <th>成绩</th>

                </tr>
                </thead>
                <tbody>

                {% for grade1 in grade %}
                <tr class="table-primary">
                    <td>{{ student.real_name }}</td>
                    <td>{{ grade1.subject }}</td>
                    <td>{{ grade1.grade }}</td>

                </tr>
                {% endfor %}


                </tbody>
            </table>
        </div>
    </div>
</div>


</body>

<script>
    $("#toExam+{{ paper1.subject }}").click(function () {

    });
</script>
</html>